### ISSUE TITLE
GPIO Low level

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1029]
Currently this feature support 2 different pins only, from pin A to pin B.

Recommend allow transfer feature on same pin so we can change pin's configuration. Example the pin speed config for high speed , user may want to try medium or low speed.

**Comment by gus-ghielec** [comment]
Then that should be a different api. Or user registers directly

**Comment by Palomino34** [comment]
Closed. Not enough important to change API. Use register will help.
