### ISSUE TITLE
SQLite: INSERT statement with multiple rows does not work

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1030]
https://forums.ghielectronics.com/t/sqlite-bugs-or-features/23755

Consider to enable SQLITE_OMIT_COMPOUND_SELECT

**Comment by greg-norris** [comment]
Consider also adding SQLITE_OMIT_BETWEEN_OPTIMIZATION

And check section #2 for possible lower memory requirement https://www.sqlite.org/compile.html

**Comment by Palomino34** [comment]
Done.
