### ISSUE TITLE
Neopixel driver first LED

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#1032]
The change in previous release broke the first LED. Maybe the issue is in the core and not the driver itself

**Comment by gus-ghielec** [comment]
I double checked the datasheet, and I believe the reset should be at the end rather than at the beginning. BUT, there is also an interesting thing it seems that in 2017 the modules changed the reset time from >50us to >280us, and the driver is using 100us reset so maybe there is a difference with the version of the 2312B (pre 2017 and post 2017)

**Comment by gus-ghielec** [comment]
I have tried it and it doesn't work at all for me with SC13

**Comment by Palomino34** [comment]
Implement native driver. Done.
