### ISSUE TITLE
WinUSB Stream - Write of buffer which is a multiple of 64 bytes causes an InvalidOperationException

### ISSUE THREAD

**Issue by taylorza** [ghi-electronics/TinyCLR-Libraries#1058]
When sending a buffer of exactly 64 bytes through WinUSB the exception below is reported. I have confirmed that if I just add a single character to the message to make the payload 65 bytes long then it works. I suspect the same issue exists in CDC since the stream implementation is the same.

```
Additional information: Exception was thrown: System.InvalidOperationException

    #### Exception System.Exception - CLR_E_PIN_UNAVAILABLE (1) ####
    #### Message: 
    #### GHIElectronics.TinyCLR.Devices.UsbClient.Provider.UsbClientControllerApiWrapper::Write [IP: 0000] ####
    #### GHIElectronics.TinyCLR.Devices.UsbClient.RawDevice+RawStream::Write [IP: 006f] ####
    #### GHIElectronics.TinyCLR.Devices.UsbClient.WinUsb+WinUsbStream::Write [IP: 0014] ####
    ...
Exception thrown: 'System.Exception' in GHIElectronics.TinyCLR.Devices.UsbClient.dll
```

I suspect the offending code is on lines 95-97 in [WinUSB.cs](https://github.com/ghi-electronics/TinyCLR-Libraries/blob/dev/GHIElectronics.TinyCLR.Devices.UsbClient/WinUsb.cs)

```
            public override void Write(byte[] buffer, int offset, int count) {
                base.Write(buffer, offset, count);

                if (count % 64 == 0)
                    base.Write(buffer, 0, 0);
            }
```

For now I have worked around the issue by chunking the data in 63 byte blocks on my side before calling WinUSB's stream Write.

**Comment by Palomino34** [comment]
Done
