### ISSUE TITLE
Why are classes sealed

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#1061]
Should we change that?

Here is more reading on the subject.

https://docs.microsoft.com/en-gb/archive/blogs/ericlippert/why-are-so-many-of-the-framework-classes-sealed

**Comment by axa88** [comment]
As a side note, besides TinyCLR-Libraries, Ive drivers for found 3rd party devices, such as [NXP PCA9685](https://github.com/ghi-electronics/TinyCLR-Drivers/blob/dev/Nxp/PCA9685/PCA9685.cs) sealed.

the driver appears a somewhat thin implementation, so is there really not any expectation a user may want to build upon it?
Having not yet learned the reasoning for sealing, finding it here hints the practice might just have become de facto without warrant?

**Comment by Palomino34** [comment]
Removed sealed.
