### ISSUE TITLE
SC13: Add backupmemory

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1076]
Use bk registers for this memory

**Comment by Palomino34** [comment]
Done

**Comment by axa88** [comment]
To confirm this is enabling RTC memory?
Will this get a target version?

**Comment by Palomino34** [comment]
Yes, but only 76 bytes for user only on SC13. It is backup registers but we can read/write single byte as well.

**Comment by axa88** [comment]
@Palomino34

I'm not familiar with "backup registers", my question is, in any way besides `total size`, does this deviate from the RTC memory description from:
https://docs.ghielectronics.com/software/tinyclr/tutorials/real-time-clock.html#battery-backed-memory

Also is there a target version?
Thanks

**Comment by Palomino34** [comment]
No different. And you even don't need to know they are "backup registers", if you don't care.
