### ISSUE TITLE
Add JsonIgnore attribute

### ISSUE THREAD

**Issue by luca-panjer** [ghi-electronics/TinyCLR-Libraries#1084]
Is it possible to get a json ignore attribute?

This way we can set properties in a class to not be serialized.

**Comment by martincalsyn** [comment]
Looks like this is not possible. You can create and set attributes on TinyClr classes, props, methods, fields, etc., but the runtime does not support enumerating them.

Attributes in mscorlib and the TinyClr libraries all seem to be either compile-time hints, or things that the runtime uses internally (e.g., MethodImplAttribute). The MemberInfo, MethodInfo, etc., classes do not include the .GetCustomAttributes reflection call that we need.

**Comment by Palomino34** [comment]
Won't fixed as [martincalsyn](https://github.com/martincalsyn) recommended.

**Comment by luca-panjer** [comment]
@Palomino34 Would it be possibvle to add the GetCustomAttributes reflection method?
