### ISSUE TITLE
passing a null string to a TextBox causes the system to hang without an error

### ISSUE THREAD

**Issue by davemclaughlin** [ghi-electronics/TinyCLR-Libraries#1086]
Passing a null string to TextBox.Text causes unpredictable behavour. This causes the software to hang and debugging stops working. Need to reset the device and use APP key to get it back working. 
Better to have the TextBox check for a null being passed in and generate an exception.

**Comment by Palomino34** [comment]
Looks to us there is no issue when give null. How did you reproduce this issue, please?

![image](https://user-images.githubusercontent.com/15822304/143889302-9cb24fd1-ad3d-4ff4-855d-ab77b8d82b05.png)

**Comment by Palomino34** [comment]
Could not reproduce.
