### ISSUE TITLE
OpenDrain doesn't work at all

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1089]
Just checked, native code doesn't process OpenDrain mode, it returns invalid agrs all the time if other than in, out, pu, pd.

**Comment by axa88** [comment]
https://forums.ghielectronics.com/t/open-drain-outputs/24031

Might there be a schedule for this?

**Comment by Palomino34** [comment]
Fixed

**Comment by axa88** [comment]
@Palomino34  updating fw to v2.1.0.6300 I do not notice the issue fixed.
This test code shows that each Gpio on my FLEA does not support Open Drain Output.

	private static void Main()
	{
		var gpioC = GpioController.GetDefault();
		OodCheck(SC13048.GpioPin.PA4);
		OodCheck(SC13048.GpioPin.PA0);
		OodCheck(SC13048.GpioPin.PA1);
		OodCheck(SC13048.GpioPin.PA5);
		OodCheck(SC13048.GpioPin.PB9);
		OodCheck(SC13048.GpioPin.PB8);
		OodCheck(SC13048.GpioPin.PA2);
		OodCheck(SC13048.GpioPin.PA3);
		OodCheck(SC13048.GpioPin.PA13);
		OodCheck(SC13048.GpioPin.PA14);
		OodCheck(SC13048.GpioPin.PA15);

		void OodCheck(int gpioPinNumber)
		{
			var ood = gpioC.OpenPin(gpioPinNumber).IsDriveModeSupported(gpioPinNumber, GpioPinDriveMode.OutputOpenDrain);
			Debug.WriteLineIf(!ood, $"pin {gpioPinNumber} no dice");
			Debug.WriteLineIf(ood, $"pin {gpioPinNumber} dice!");
		}
		Thread.Sleep(Timeout.Infinite);
	}



pin 4 no dice
pin 0 no dice
pin 1 no dice
pin 5 no dice
pin 25 no dice
pin 24 no dice
pin 2 no dice
pin 3 no dice
pin 13 no dice
pin 14 no dice
pin 15 no dice


I included new Lib 2.1.1 for good measure but nothing is changed there.
Something im missing?
Please advise.

**Comment by Palomino34** [comment]
Looks to me that any gpio pin support open-drain as well. So just config the pin you want OD. No need to check by "IsDriveModeSupported"

**Comment by axa88** [comment]
> No need to check by "IsDriveModeSupported"

But wouldn't reporting the correct state here be part of the fix?? Why have the property if it only adds confusion?

**Comment by Palomino34** [comment]
Since all gpio support open-drain then this function to me, it is useless. You can ignore it and go ahead with setting OD.
We will look into more in next release, but it is not important.

**Comment by axa88** [comment]
> Since all gpio support open-drain then this function to me, it is useless. You can ignore it and go ahead with setting OD. We will look into more in next release, but it is not important.

Now I see why you're saying, there really isn't any practical use when the eatures are functioning. 
my use case was really due to the drive mode being broken.
