### ISSUE TITLE
ArrayList.Copyto does not work on some DataType fully.

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1163]
So far TimeSpan does not work if use Copyto

https://forums.ghielectronics.com/t/signalgenerator-write-failed/24299/13

**Comment by Implicate-X** [comment]
ToArray does not work any more than CopyTo.

Example:
`( TimeSpan[] )tapeDataByte.ToArray( typeof( TimeSpan ) )`

**Comment by Palomino34** [comment]
Have workaround, closed.
