### ISSUE TITLE
Shutdown mode sometime higher power consumption.

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1220]
Fixed by set all pins need to be pulldown if used.

Example: 
UART-> dispose -> set input pulldown manually.
LED -> dispose-> set input pulldown manually.
...

It is OK because shutdown no need to resume, it will reset everything after wakeup anyway.

Only SDRAM need native pin free. Firmware will do that.

**Comment by Palomino34** [comment]
Could not reproduce on SC20260D

**Comment by MMajo** [comment]
With version 2.3.0.1000 on the SCM20260N with extend heap enabled, the 20mA shutdown consumption started to occur frequently again.
