### ISSUE TITLE
Sometime ADC gets Invalid exception when change from MSC mode to WinUsb mode

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#1338]
https://forums.ghielectronics.com/t/switching-between-winusb-and-massstorage-usb-modes/24501/47

**Comment by c-born** [comment]
I see this only when turning Mass Storage mode on

**Comment by Palomino34** [comment]
because only MS is on and using try catch will help. Not fix now,
