### ISSUE TITLE
Generate TCA file even when deploying to a device in Visual Studio

### ISSUE THREAD

**Issue by skeller2015** [ghi-electronics/TinyCLR-Libraries#1360]
Generate the .tca file even when Transport = USB and deploying to the device when in Visual Studio.

This eliminates the additional steps required to use TinyCLR Config application to generate the tca file.

**Comment by Palomino34** [comment]
It would be nice if have this, but most of the time users don't need this, it will slow down or effect the deployment

Just select "generate tca and raw...." and user will have tca file.

**Comment by skeller2015** [comment]
I understand it slows the deployment but a simple check box to have it as an option would be helpful.   This would be similar to other embedded development environments that generate a usable output file on each compile.

**Comment by Palomino34** [comment]
We will look into it.

**Comment by Palomino34** [comment]
In stead of checking on the check box, user can switch them in the combobox.
