### ISSUE TITLE
Feature Request: Websocket

### ISSUE THREAD

**Issue by rdpeake** [ghi-electronics/TinyCLR-Libraries#1364]
Is it possible to add websocket support to the tinyclr networking stack, or would adding c# async/await support to tinyclr mscorlib allow the native websocket to work. Or is this a limitation of the wifi chips. For me specifically i am trying to use a fez portal and home assistant via websocket.

**Comment by Palomino34** [comment]
These are supported by Endpoint: https://www.ghielectronics.com/endpoint/

Currently no plan to add this to SITCore.
