### ISSUE TITLE
Slim down mscorlib

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Libraries#199]
Only the essentials for compiling and commonly uses. Threading, exceptions, primitive types, compile attributes, etc.

StringBuilder, MemoryStream, and such can be another library. ArrayList, HashTable, etc could probably be another Collections library.

mscorlib adds about 70kb to deployment which is a lot.

**Comment by gus-ghielec** [comment]
This is only a concern if tiny hardware option was to be introduced. Current hardware has plenty of resources.
