### ISSUE TITLE
Ensure images can be loaded from files

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Libraries#321]
The bitmap class has a constructor that takes a stream, but that eventually gets passed down to the internal bitmap that only specifies bmp type, we need to read the read and pass down gif/jpg/bmp, etc. See if there are other ways to make images.

**Comment by Palomino34** [comment]
Reopen

**Comment by Palomino34** [comment]
We added 

public Bitmap(byte[] buffer, int offset, int count, BitmapImageType type)

And as tested with Window BMP, JPEG, GIF work fine when read data from file, instead of resource only.
