### ISSUE TITLE
Can't build the libraries projects

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#481]
The projects each contain a packages.config file that references assemblies that are not available outside of GHI:

```
<package id="GHIElectronics.Tools.AssemblySigner" version="1.0.3" targetFramework="net452" developmentDependency="true" />
<package id="GHIElectronics.Tools.NuGetPacker" version="1.0.3" targetFramework="net452" developmentDependency="true" />
```

I'd love to contribute more PRs, but that's made harder because I can't build the debug versions or the nuget packages for testing.  I can build raw dlls by editing all of the package.config files and just not committing those changes, but it shouldn't be that hard.

SUGGESTION: Check in the nuget packager, and check in a signer that fails (succeeds?) silently if GHI signing keys are not found.

**Comment by Palomino34** [comment]
We will take a look. Thanks.

**Comment by martincalsyn** [comment]
This has been partially resolved with the changes Dat made in the merge commit fa67658587d2861a5716ccd5821e14ed531314e3
