### ISSUE TITLE
IsEnabled has no effect on control input

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#485]
If you set IsEnabled = false on a TextBox, the user can still touch/click that textbox and the on-screen keyboard appears, and any changes made on the keyboard are applied to the text value.

Essentially, IsEnabled doesn't do anything, so one cannot create a conditionally read-only TextBox

**Comment by martincalsyn** [comment]
Changed the title.  It turns out that IsEnabled is not affecting most controls.  IsEnabled=false should prevent that control from firing input events. Disabled controls must not accept input from the user.

**Comment by Palomino34** [comment]
Fixed by #497
