### ISSUE TITLE
Exceptions in event handlers leave the UI corrupted

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#498]
If a user attaches an event handler to the 'Clicked' event on a button (or probably any other control) and the event handler throws, then the control is left in a bad visual state. That is, it looks like it is still pressed. I'm sure most other controls exhibit similar issues because none of the calls to the event handlers are protected by exception wrappers and most have 'tail' code after the delegate call.

Calls to Click and similar delegate functions either need to be wrapped in try/finally to make sure that the tail code runs and updates the UI, or, the call to the event handler should happen after the control has been returned to a good state (e.g., there is no tail code after the call to the event handler).

**Comment by Palomino34** [comment]
Fixed.
