### ISSUE TITLE
New keyboard contains wrong keycap

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#501]
The new resources for the 800x320 keyboard gifs contain a "RETURN" keycap, but when you press the button it does a "BACKSPACE".  It looks like that keycap should show the <- backspace/delete icon (a left-facing flag with an X in it).

**Comment by martincalsyn** [comment]
All three keyboard images have the same problem

**Comment by greg-norris** [comment]
Fixed in latest pull request.
