### ISSUE TITLE
PulseFeedback doesn't seem to work

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#506]
Verify operation and improve docs to show the different uses:

1. Use with ultrasonic sensor...generate pulse and measure feedback. PulseFeedbackMode.EchoDuration
2. Use with cap touch: charge a cap and measure discharge time. PulseFeedbackMode.DrainDuration
3. There was a third use of time to response that we no longer use. Perhaps remove or find a way to test PulseFeedbackMode.DurationUntilEcho

**Comment by Palomino34** [comment]
Duplicate #528
