### ISSUE TITLE
Networking diagnostics

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#508]
Is there a way to get diagnostic info from the TCP and TLS stacks? Can we also add more info the receptions to help users determine what is going on.

**Comment by gus-ghielec** [comment]
Here is an example https://forums.ghielectronics.com/t/an-http-s-error-stumped-by-a-lack-of-diagnostic-info/22810

**Comment by Palomino34** [comment]
Wil not support
