### ISSUE TITLE
File information calls return "Not yet implemented"

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#510]
I can't get file information (like last write time) because the underlying call returns a not-yet-implemented exception.  This is pretty core functionality.

```
        private bool UpdateFile(string url, FileInfo fi)
        {
            bool result = true;

            DateTime lastWriteTime = DateTime.MinValue;
            if (fi.Exists)
            {
                lastWriteTime = fi.LastWriteTimeUtc; <-- Throws an exception
            }

            this.CopyFromWebIfNewer(url, fi, lastWriteTime);

            return result;
        }

```

The exception originates here : 

Line 77 in FileSystemInfo.cs : 
`                this._nativeFileInfo = DriveInfo.GetForPath(this.m_fullPath).GetFileSystemEntry(this.m_fullPath);
`

Looks like it is not implemented in the native code component.

**Comment by Palomino34** [comment]
fixed

**Comment by martincalsyn** [comment]
👏👍
