### ISSUE TITLE
UI Library items contain Dispose(), but don't inherit from IDisposable

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#524]
Multiple classes in the UI library (Button for instance) contain:

`public void Dispose()`

...however, the classes do not inherit from IDisposable anywhere in their inheritance chain and it doesn't look like the Dispose method ever gets called.

These classes should implement a proper IDisposable pattern to get memory cleaned up quicker.

**Comment by mifmasterz** [comment]
I have applied this fix to https://github.com/Gravicode/GlideX

**Comment by martincalsyn** [comment]
But the fix in Gravicode only adds the interface - it doesn't actually call the Dispose in the right places

**Comment by mifmasterz** [comment]
yes, I didn't see where the "dispose" method is called..

**Comment by Palomino34** [comment]
Closed by #610.
