### ISSUE TITLE
OnScreenKeyboard should have a 'cancel' button

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#526]
I almost feel guilty for entering another OSK bug ... almost.

The on-screen-keyboard has a 'done' button, but no 'cancel' button.  If you mess up data entry and can't remember what the original value was, there's no way out for you.

There should be an 'Esc' or 'Cancel' button to allow users to bail out of data entry without making a change.

**Comment by mifmasterz** [comment]
![image](https://user-images.githubusercontent.com/15245579/82306938-e82e4e80-99e9-11ea-9ddb-e432733ff683.png)
now, it has cancel button.. but still in https://github.com/Gravicode/GlideX

**Comment by gus-ghielec** [comment]
Great! Are you going to be sending a PR?

**Comment by mifmasterz** [comment]
yes, but too many changes I've been done in UI library.. so, I need to separate the changes first

**Comment by Palomino34** [comment]
No need cancel button. Done button is enough. Closed.
