### ISSUE TITLE
Improve pulse feedback

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#528]
- Change constructor from int to gpio
- Remove GPIOController from the constructor (we now have 4 overloads, but we only need 2)
- Rename GeneratePulse() with Trigger()
- Remove PulsePinDriveMode
- Remove EchoPinDriveMode
- Rename PulsePinValue to PulseValue
- DrainDuration only works with one pin, trig and no echo. If 2 pins are set then raise exception
- DurationUntilEcho and EchoDuration must have 2 pins, trig and echo. If only one pin then raise exception

FEZ Bit touch pads Doesn't work
```
static void TestTouchPads() {
            var pulse = new PulseFeedback(FEZBit.GpioPin.EdgeP0,
                PulseFeedbackMode.DrainDuration) { 
                DisableInterrupts = true,
                Timeout = TimeSpan.FromSeconds(1),
                PulseLength = TimeSpan.FromMilliseconds(1),
                PulsePinValue = GpioPinValue.Low,
                //EchoPinValue = GpioPinValue.High,
                //PulsePinDriveMode = GpioPinDriveMode.Input,
                //EchoPinDriveMode = GpioPinDriveMode.Input
            };

            while (true) {
                var d = pulse.GeneratePulse(); ;

                Thread.Sleep(250);
            }
        }
```

**Comment by Palomino34** [comment]
Verify operation and improve docs to show the different uses:
Use with ultrasonic sensor...generate pulse and measure feedback. PulseFeedbackMode.EchoDuration
Use with cap touch: charge a cap and measure discharge time. PulseFeedbackMode.DrainDuration
There was a third use of time to response that we no longer use. Perhaps remove or find a way to test PulseFeedbackMode.DurationUntilEcho
