### ISSUE TITLE
Add software PWM support

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#543]
A simple internal timer that triggers on next edge so it does not interrupt too frequently. We do not need very high frequency, dim LED and control Servo is enogh.

Can DMA be use with comparator to eliminate the need for interrupts?

**Comment by gus-ghielec** [comment]
This must work on any pin. Using DMA will not likely work. Use native threads to process and limit the frequency to low value that uses less than 1% of the system resources.

**Comment by Palomino34** [comment]
Added
