### ISSUE TITLE
WiFi AP mode

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#546]
Can we enable WiFi AP mode, where WINC1500 become an AP that someone can connect to directly from a phone?

Is this needed? How complex it is? Research and determine the need.

**Comment by martincalsyn** [comment]
This is super important.  It's an essential part of the onboarding strategy for UI-less IoT devices.  Think about how you onboard a new Alexa for instance - Alexa (and similar devices) create an AP with a well-known SSID shape, The phone app scans for those SSID's and connects to one and allows you to use the phone app over the ad-hoc wifi connection to do the initial first-run setup.

**Comment by Palomino34** [comment]
Added
