### ISSUE TITLE
Check the button even 

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#548]
Issue reported here https://forums.ghielectronics.com/t/button-click-gets-called-twice/22774

**Comment by Palomino34** [comment]
Click can be up or down. This is also needed if we want to measure how long we pressed.

If need only one event, it is easy to do the compare the event name:

```
if (e.RoutedEvent == TouchEvents.TouchUpEvent) {
    // do something or skip
}
else {
  // do something or skip
}
```
