### ISSUE TITLE
Screen Capture

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#549]
This feature helps customers in making documentation for their end products. Ideally, we convert the captured data into standard BMP file that we can save. 

Converting data to BMP file is another potential feature while we do this work.

**Comment by Palomino34** [comment]
User can subscribe graphic event and get all data in screen.
Also, similar to bitmap class, graphics also has an API graphic.GetBitmap(), this will return an array of full screen.

Byte those ways, user can capture both SPI and native screen.
