### ISSUE TITLE
Regular Expression

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#556]
Should this be a standard and documented features of TinyCLR? This is a good read https://www.codeproject.com/Articles/386890/String-Manipulation-in-the-NET-Micro-Framework

**Comment by gus-ghielec** [comment]
Look what I have found in the archive https://forums.ghielectronics.com/t/regular-expression-regex-we-have-one/7281

**Comment by Palomino34** [comment]
Added
