### ISSUE TITLE
CAN bus RX fifo error

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#562]
Under stress, CAN will miss a message but the message is received on the next event. Ether events are not fired correctly or the user is not handling RX events properly.

See here https://forums.ghielectronics.com/t/can-bus-errors/22982

**Comment by gus-ghielec** [comment]
Combine this with #544

**Comment by Palomino34** [comment]
Event lost, not message. User poll messages are still there in buffer.
