### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#570]
We have JSON so XML is not necessary but by not add anyway?! We can do it all C# and it will simply not use any additional firmware space. Or add native mix and make it super fast.

**Comment by martincalsyn** [comment]
I am sure there are applications where this would be useful, but I'd definitely put it in a separate assembly because proper XML parsing is complicated and the parser will make for a fairly large assembly - large enough that you wouldn't want to pull it in if you don't need it.

**Comment by Palomino34** [comment]
We added XML
