### ISSUE TITLE
GPS library

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#575]
Need a tightly built, efficient library, to parser GPS streams

**Comment by mifmasterz** [comment]
ported from netduino sample to tinyclr : https://github.com/mifmasterz/GPSParser.git 
I haven't tried it with real gps module, please take it

**Comment by gus-ghielec** [comment]
There has been multiple GPS parser over the years. The challenge here is writing an efficient one that takes under consideration system heap fragmentation. GPS is very simple but at if the stream comes in once per second, non stop.

I did not review your code so I do not know. I also see you have included regular expressions so this ties into #556

**Comment by mifmasterz** [comment]
this parser is from netduino version, so it must be worked for netmf, but yes we need to improve it's code for TinyCLR
