### ISSUE TITLE
Configuration.Read() does not return the requested number of bytes

### ISSUE THREAD

**Issue by ghost** [ghi-electronics/TinyCLR-Libraries#592]
Using the following code, you only get the first 8 bytes in the 'rdata' array : 

```
private static void TestConfiguration()
        {
            Debug.WriteLine("Writing buffer....");
            var data = new Byte[] { 0x01, 0X02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A };
            Configuration.Write(data, 0, 0, (UInt32)data.Length);

            Debug.WriteLine("Read configuration....");
            var rdata = new Byte[10];
            Configuration.Read(rdata, 0, 0, 10);
        }

```
Values 0x09 and 0x0A are not returned.

However, if you read 12 bytes, then you get your expected 10 bytes.
That seems to mean that you have to read your configuration data in 4-bytes chuncks. I've tried with 6 bytes to read and got the same behavior : read 6 - get 4, read 8 - get 8.

**Comment by Palomino34** [comment]
Yes, it requires 4 bytes alignment to read, 32 bytes to write. We will document these.

Thanks.
