### ISSUE TITLE
Garbage collection documentation does not match current API?

### ISSUE THREAD

**Issue by NJ08512** [ghi-electronics/TinyCLR-Libraries#612]
On https://docs.ghielectronics.com/software/tinyclr/tutorials/memory.html

The APIs Debug.GC(true) and Debug.EnableGCMessages(true) discussed in the documentation are not in Preview 6.

Mike

**Comment by Palomino34** [comment]
We just added Debug.EnableGCMessages(true)  back.

Debug.GC(true) => You can use "System.GC.GetTotalMemory(true);"
