### ISSUE TITLE
Using foreach to enumerate a string results in a build error

### ISSUE THREAD

**Issue by NJ08512** [ghi-electronics/TinyCLR-Libraries#619]
TinyClr preview 6

The following code builds and executes correctly with a PC console application, but results in an error when building a tinyClr application.

The Tincyclr build error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7038	Failed to emit module 'TinyCLRApp': Unable to determine specific cause of the failure.	TinyCLRApp	C:\Users\Mike\source\repos\ForeachOnStringTest\TinyCLRApp\CSC	1	Active

The code:
```
using System.Text;

namespace TinyCLRApp
{
    class Program
    {
        static void Main()
        {
            StringBuilder sb = new StringBuilder(128);
            string ts = "This is a test message";
            foreach (char c in ts)
            {
                sb.Append(c);
            }
            string ts2 = sb.ToString();
        }
    }
}


.. Mike ...

**Comment by Palomino34** [comment]
duplicate #323.
