### ISSUE TITLE
In Pins PH11 pin is missing for SC20260D board

### ISSUE THREAD

**Issue by bauland** [ghi-electronics/TinyCLR-Libraries#644]
In rc1, there is no SC20260.GpioPin.PH11 (which is connected on led) in Pins library.

**Comment by Palomino34** [comment]
What do you mean "no SC20260.GpioPin.PH11"?

I have checked, it is there. 

You can check Demo on SC20260, I believe this project also uses  SC20260.GpioPin.PH11.

**Comment by bauland** [comment]
Sorry, it is my fault: order of variables is incorrect:
![pin1](https://user-images.githubusercontent.com/13621705/87881021-b855f400-c9f6-11ea-8f6e-52740b72b4e9.png)
but it exists indeed:
![pin2](https://user-images.githubusercontent.com/13621705/87881031-c6a41000-c9f6-11ea-86a9-808f5e042247.png)
even it is not at expected place (order is not what I believe !). 
Issue can be closed and I owe you some beers !

**Comment by Palomino34** [comment]
Not a bug.
