### ISSUE TITLE
Support MSB LSB on spi

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#673]
Only if the processor itself supports it and we only need to add a flag to activate

**Comment by Palomino34** [comment]
We do already have it, in bit. 

In setting,

```
 DataFrameFormat = SpiDataFrame.MsbFirst // or
 DataFrameFormat = SpiDataFrame.LsbFirst
```

No support byte. Do BitConverter to swap the array if need in byte for large array, if speed is important.

**Comment by gus-ghielec** [comment]
Needs to be documneted
