### ISSUE TITLE
Raise exception if DataBits = 8 and Parity.Even

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Libraries#695]
Parity.Even need DataBits = 9.

Just raise exception if DataBits = 8

**Comment by MBNSoftware** [comment]
Parity bit is not tied to data bits. It is an additional bit in the serial frame.
You can have any size in DataBits (from 5 to 9) and still have a parity bit. Both "7-Even-1" and "9-Odd-1" (DataBits-Parity-Stop) are valid.
Granted, we see 7-E-1 or 8-N-1 more often, but there are no reason to prevent the use of other valid parameters, to me.

So I would not raise an exception in that situation.

**Comment by Palomino34** [comment]
Agreed that.

**Comment by Palomino34** [comment]
Fixed
