### ISSUE TITLE
Initializing the ATWINC with null ssid and password hangs system

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#716]
If you pass null for ssid and password in WiFiNetworkInterfaceSettings, then .SetInterfaceSettings may hang long enough for the debugger to detach, and/or .Enable may hang permanently in unmanaged code.  On the other hand, empty strings for these values hang for tens of seconds, but not long enough for the debugger to detach. And yes, null is an invalid value, but even invalid values should not hang the interpreter.

EXPECTED:
Invalid values to be rejected immediately, or at least not hard-hang in unmanaged code
In general, PInvoke calls should not last so long that the debugger detaches

OBSERVED:
Hard hangs and debugger detach due to timeout

REPRO:
```
                WiFiNetworkInterfaceSettings wifiSettings = new WiFiNetworkInterfaceSettings()
                {
                    Ssid = null,
                    Password = null
                };
                wifiSettings.IsDhcpEnabled = true;
                // next two calls will hang hard or time out
                networkController.SetInterfaceSettings(wifiSettings);
                networkController.Enable();

```

**Comment by Palomino34** [comment]
Fixed
