### ISSUE TITLE
CAN Peripheral sets available messages to 0

### ISSUE THREAD

**Issue by luca-panjer** [ghi-electronics/TinyCLR-Libraries#725]
As discussed on the forum [here](https://forums.ghielectronics.com/t/can-bus-limitations/23380/18), the CAN peripheral sometimes bugs out and sets the MessagesToRead property to 0 while there are still messages being received. 

This can be fixed by disabling and enabling the can peripheral. The problem then disappears for a random amount of time.

I have uploaded a project [here ](https://github.com/TGlev/CAN-Speed-Test)that can be ran to see the issue for yourself. At a load of about 500 messages per second (sometimes lower, sometimes higher) this issue starts happening. All the example project is doing is reading can messages as fast as possible in the main loop and sending them over UDP. Removing the line where the UDP packet is sent, fixes the problem. Also, there are no CAN error events triggered.

**Comment by Palomino34** [comment]
Thanks a lot. We found and fixed the issue.
