### ISSUE TITLE
Path.Combine does not de-duplicate separators

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#756]
REPRO:
            var leftpart = @"test\path\";
            var rightpart = "index.html";
            var result = Path.Combine(leftpart, rightpart);
            Debug.WriteLine(result);

EXPECTED:
result == test\path\index.html

RESULT:
correct result on dotnet core and framework
result == test\path\\\\index.html on TinyCLR

TinyCLR should de-duplicate path separators.

**Comment by gus-ghielec** [comment]
Both results are the same on your email but I am guessing they're is an extra / in TinyCLR

Regards,

Gus Issa
---
Please excuse brevity or typos, this was entered on a phone!

________________________________

**Comment by martincalsyn** [comment]
Interesting.  Markdown failure.  I typed it correctly but markdown messed with it.
Anyway, I edited the original report. The 'Result' section shows the error now.

**Comment by Palomino34** [comment]
As quick test, it look good to me.


![image](https://user-images.githubusercontent.com/15822304/102411088-72aa5100-3fbf-11eb-8a43-fa80b1bd4336.png)
