### ISSUE TITLE
SPI buffer size limited to 65535 bytes

### ISSUE THREAD

**Issue by MBNSoftware** [ghi-electronics/TinyCLR-Libraries#758]
Trying to send more than `UInt16.MaxValue` throws an "Invalid operation exception" :

>     #### Exception System.InvalidOperationException - CLR_E_INVALID_OPERATION (1) ####
>     #### Message: 
>     #### GHIElectronics.TinyCLR.Devices.Spi.Provider.SpiControllerApiWrapper::WriteRead [IP: 0000] ####
>     #### GHIElectronics.TinyCLR.Devices.Spi.SpiDevice::WriteRead [IP: 001d] ####
>     #### GHIElectronics.TinyCLR.Devices.Spi.SpiDevice::Write [IP: 000b] ####
>     #### MBN.Modules.ILI9341.ILI9341Controller::DrawBuffer [IP: 0053] ####
>     #### ILI9341.Program::Graphics_OnFlushEvent [IP: 0008] ####
>     #### System.Drawing.Graphics::Flush [IP: 002d] ####
>     #### ILI9341.Program::Main [IP: 000b] ####
> Exception levée : 'System.InvalidOperationException' dans GHIElectronics.TinyCLR.Devices.Spi.dll

**Comment by Palomino34** [comment]
added
