### ISSUE TITLE
EnableExternalFlash

### ISSUE THREAD

**Issue by greg-norris** [ghi-electronics/TinyCLR-Libraries#760]
Is this correct or it should be ExtendDeployment?

**Comment by greg-norris** [comment]
Update doc GHIElectronics.TinyCLR.Native.Flash.EnableExternalFlash() also  (ExternalMemory.md)

**Comment by gus-ghielec** [comment]
The system should only set if QSPI was detected in power up. The IsEnableExternalFlash shuld only get set if all worked as expected

**Comment by Palomino34** [comment]
Fixed.
