### ISSUE TITLE
NetworkStream.Write() fails on partially completed Send()

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#765]
NetworkStream.cs Write() throws an exception at line 410 if the bytesSent are not equal to the count of bytes to be sent.  Instead, it should try to send the remainder.  Partial sends might be expected for TCP streams. The code should re-try the send using just the 'remainder' bytes and then fail only if 0 of those got sent.  The same might be true for UDP if we try to send more bytes than will fit in a frame.  In that case, I'm not sure what the proper action should be.

**Comment by martincalsyn** [comment]
PR submitted (PR #766 766)

**Comment by Palomino34** [comment]
Done
