### ISSUE TITLE
Large SPI Displays speed

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#777]
Investigate possible improvements for "write only" operations that requires highest speed, like when refreshing a 320x240 SPI display. There is no read but we must write 150KB as quickly as possible.

See [this](https://forums.ghielectronics.com/t/spi-buffer-size-limited-to-65535-bytes/23448/10)

**Comment by Palomino34** [comment]
240x320*2*8 =1,228,800 bit.

At 12MHz max 10fs,
At 24MHz max 20fps.

Tested on 240x320 SITCore get that values with is maximum we can do.

Also do on scope there is no gap between 2 bytes at 30MHz.
