### ISSUE TITLE
Enable parameters retrieval for Graphics.Flush(x,y,w,h) in the Flush event handler

### ISSUE THREAD

**Issue by MBNSoftware** [ghi-electronics/TinyCLR-Libraries#778]
Currently, only the whole buffer is accessible, thus rendering this Flush() overload unusable.

**Comment by Palomino34** [comment]
Addef

**Comment by MBNSoftware** [comment]
How do you use the new "sender" parameter ?

**Comment by Palomino34** [comment]
Sender is a graphic object.
Gfx160x128 = Graphic.FromImage(,.....);
Gfx320x240 = Graphic.FromImage(,.....);

Gfx160x128.Flush();
Gfx320x240.Flush();

.....
Event:

if (sender == Gfx160x128) {
        //Send to screen 160x128;
        160x128Driver.DrawBuffer(.....);
}

if (sender == Gfx320x240) {
       /// Send to screen 320x240;
         320x240Driver.DrawBuffer(.....);
}
