### ISSUE TITLE
Mac address values are not consistent

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#795]
This code will give two different answers:

```
                    var mac = Winc15x0Interface.GetMacAddress();

                    var ifprops = networkController.GetInterfaceProperties();
                    var mac = ifprops.MacAddress;

```

The first one will give you the MAC addr that is provided with the Winc15x0 chip, and the second will give all zeros until you complete the initialization.  It would seem that if a valid MAC addr is available, then the second call should also return that value.

**Comment by martincalsyn** [comment]
And this returns yet another value after an AP client connects:

```
        private void WifiSettings_AccessPointClientConnectionChanged(NetworkController sender, IPAddress clientAddrres, string macAddress)
        {
            Debug.WriteLine("AP Client Connected : " + clientAddrres.ToString() + " mac: " + macAddress);

```

**Comment by Palomino34** [comment]
NetworkController.MacAddress  only valid after completed initialize.  

```
private void WifiSettings_AccessPointClientConnectionChanged(NetworkController sender, IPAddress clientAddrres, string macAddress)
        {
            Debug.WriteLine("AP Client Connected : " + clientAddrres.ToString() + " mac: " + macAddress);
```

That MAC is from client connect to AP, not from WiFi.

**Comment by martincalsyn** [comment]
Yup - just realized that and came back to delete my silly comment, but you beat me to it - color me sheepish.
However, the original issue still stands.  The two APIs return different values (and all zeros isn't really useful, so I feel like that API should return the default from the winc chip).

**Comment by gus-ghielec** [comment]
there isn't much to fix here. Maybe a note in docs that no one will likely see!
