### ISSUE TITLE
Json: Polymorphic types are serialized as the base type

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#796]
If you have types B and C which both inherit from type A, and a property of type A on some object 'obj', then upon serialization of 'obj', the property of type A will be serialized as an instance of type A regardless of whether it holds a value of type B or C.

This means that the specializations and additional properties that may be present in B and C will not be serialized.  This is especially obvious if you have a property of type 'object', in which case nothing gets serialized other than an empty object regardless of what that reference was pointing to.

I have a fix in the works that chooses the type based on the actual type of the object referenced (if non-null) rather than the return type of the property, but I need to work out how to handle that on de-serialization. Probably some combination of a "$type" member and/or the InstanceFactory delegate.

**Comment by gus-ghielec** [comment]
Thanks for the fix
