### ISSUE TITLE
Clear screen when initialized

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#807]
Internal graphics can show garbage on the screen when initialized. Clear the screen buffer

**Comment by MBNSoftware** [comment]
It could be a optional parameter, set to true (clear screen) by default.
Sometimes it's useful to see garbage on the screen : it clearly shows where you are writing on the display.

Or, if you don't like to see garbage, add a Clear(RGBColor) overload ?

**Comment by gus-ghielec** [comment]
In a commercial use having garbage is not okay. What you are asking for is good for debugging only. You can subbing flush something useful instead.

**Comment by Palomino34** [comment]
- We fixed in Native display.
- Other displays (N18, ILI9341...), we won't fix because those screen don't use internal buffer. It takes the buffer from user directly, and transfer to the target devices. We don't want to create an internal for temporary buffer just for flushing to clear the screen.
