### ISSUE TITLE
Track changing graphics

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#809]
The graphics library supports partial update through Flush(x, y, width, height). This great but how do we know what pixels have changed?

```
Graphics.WriteText(5, 10, "Hello");
Graphics.Flush(5, 10, ?, ?);
```
The internal engine should track the lowest/highest changing pixels on x and y and then it can easily provide this info. Even better, automatically send the info so the user will only need to do Flush()

**Comment by MBNSoftware** [comment]
Public read-only properties would be useful as well, as we may not flush immediately after a graphic action.

**Comment by gus-ghielec** [comment]
This will only let track and not flush. It is up to you to flush when need

**Comment by gus-ghielec** [comment]
The user have better tracking on what they need updated
