### ISSUE TITLE
Neopixel driver

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#818]
The signal generator can generate okay signals to handle smart LEDs but there seen to be noise across the lines. Is it timing issue and can it be fixed? Likely can't get ns accuracy and so we need to implement a native handler with great accuracy

**Comment by gus-ghielec** [comment]
Can we create a generic hardware dma signal generator?

**Comment by Palomino34** [comment]
We have added hardware signal generator but a dedicated driver will save a lot of RAM

**Comment by Palomino34** [comment]
Done. hardware added
