### ISSUE TITLE
SD cards over SPI

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#819]
Add support for SD/MMC cards over SPI bus.

Does using hardware CS make it faster? If so should we include HW CS pin?

**Comment by gus-ghielec** [comment]
Not needed as all current devices provide a pepper 4bit interface

**Comment by Palomino34** [comment]
Reopen. We need for SC13xxx

**Comment by Palomino34** [comment]
it can be implemented in c#. Closed.
