### ISSUE TITLE
 N18 display speed

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#820]
Devices such as FEZ Bit may need a faster update speeds and they are okay with 8BPP. We already have color space conversion. Give the user the option to select 8BPP and the color map table.

Even do 4BPP if the controller supports it. I think it does not

**Comment by gus-ghielec** [comment]
Looks like 8BPP is not supported but 12BPP is. Determine if the additional memory usage outweighs the speed improvement. 128×160×1.5 is 30KB!

Determine if we can increase the SPI clock speed. Give users the option to set the clock.

**Comment by Palomino34** [comment]
We implemented 12BPP.

Note: Image only correct when 4 bytes (565-2pixels) to 3 bytes (444 - 2pixels).

Meaning X and Width of an object on image must be multiply of 2, if want object is displayed correctly.

**Comment by Palomino34** [comment]
Work perfectly now, no need x or width must be multiply 2.
