### ISSUE TITLE
Support additional WiFi modules

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#822]
Add another wifi option, perhaps a lower cost espressif option. Security and circuital quality must be maintained. The support must be native and uses the built in .net sockets, just like the current option does.

**Comment by MBNSoftware** [comment]
Is it possible to "open" the current API or have methods exposed that allow the addition of any module ?

**Comment by gus-ghielec** [comment]
Not possible for security concerns. All handling is fine on native side securely.

**Comment by Palomino34** [comment]
Will not support. Users can use AT commands with ESP32 if needed
