### ISSUE TITLE
text has no background

### ISSUE THREAD

**Issue by jooos5** [ghi-electronics/TinyCLR-Libraries#829]
had to use edit boxes and set the background and set enable to false

**Comment by AndreMarschalek** [comment]
its unclear to me what you mean, please can you provide more information, may be with sample code and/or pictures?

**Comment by jooos5** [comment]
Text (control UI) does not have a background property

**Comment by AndreMarschalek** [comment]
the background of the text is the color of the parent element
it is possible to add background color property but where should this background begin and end?
i am not sure if not an additionally horizontal and vertical padding property make sense like the textbox

**Comment by gus-ghielec** [comment]
Closing till we have a better understanding of the need
