### ISSUE TITLE
Add an animation engine

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#830]
Add an animation engine that can vary any numeric property of a visual object according to keyframes and curves.

The animation step can either be driver by a timer interrupt or a frame-advance call from user code. Probably should support both options since the timer would affect execution speed, and the frame-advance could result in jumpy visuals, so the choice would depend on what the programmer values most : smooth compute or smooth animation.

**Comment by gus-ghielec** [comment]
This is a stretch goal as TinyCLR is not meant to be a media player. If simple animation is needed then use MJPEG https://docs.ghielectronics.com/software/tinyclr/tutorials/mjpeg-video.html
