### ISSUE TITLE
Reason for waking up

### ISSUE THREAD

**Issue by MMajo** [ghi-electronics/TinyCLR-Libraries#839]
Add a reason to wake up from shutdown and sleep mode (PIN or RTC).

**Comment by gus-ghielec** [comment]
And iif watchdog or brownout

**Comment by Palomino34** [comment]
Reading bit 8 in RTC_ISR for wakeup RTC status. Wakeup registers don't tell about rtc or pin

**Comment by Palomino34** [comment]
Done
