### ISSUE TITLE
Webusb

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#840]
Investigate if any changes are needed in USB client to support webUSB

https://wicg.github.io/webusb/

**Comment by gus-ghielec** [comment]
It maybe easiest to start by emulating this project https://github.com/sowbug/weblight

You can then just to go the following page to try it
https://sowbug.github.io/weblight/

**Comment by gus-ghielec** [comment]
This is a good read https://web.dev/usb/

**Comment by gus-ghielec** [comment]
Test with android as well

**Comment by Palomino34** [comment]
Added BOS with WebUsb enable.
