### ISSUE TITLE
NetworkStream Timeout Behavior

### ISSUE THREAD

**Issue by pdcompto1** [ghi-electronics/TinyCLR-Libraries#841]
NetworkStream returns 0 when either a send/read timeout occurs or when the remote device requests to close the connection. The proper behavior is to return an IOException when a timeout occurs and 0 when the remote device requests the connection to be closed. 

Repro: Open a NetworkStream with a read timeout set.   Call NetworkStream.Read() and print return value.  After timeout, 0 will be returned instead of an IOException.  To test the other scenario, set an infinite timeout, connect to a remote device, then call NetworkStream.Close() on the remote device.  NetworkStream.Read() should then return 0.

**Comment by Palomino34** [comment]
Fixed
