### ISSUE TITLE
Base64 Encoding/Decoding

### ISSUE THREAD

**Issue by skeller2015** [ghi-electronics/TinyCLR-Libraries#854]
A native Base64 encode/decode functions would be nice.
In desktop .NET framework it is located under System.Convert.ToBase64STring() and .FromBase64String()

**Comment by gus-ghielec** [comment]
I think we have it. Maybe one the http library. But it will be nice to move to buy converter on the future perhaps. We will check.

**Comment by skeller2015** [comment]
It is already in System.Convert but is not browsable due to [EditorBrowsable(EditorBrowsableState.Never)] in the Convert class.

**Comment by Palomino34** [comment]
We changed to Never -> Always.
