### ISSUE TITLE
Image/Bitmap inconsistent implementation

### ISSUE THREAD

**Issue by taylorza** [ghi-electronics/TinyCLR-Libraries#878]
`System.Drawing.Image` implements `SetPixel`, which is unnecessarily reimplemented in `System.Drawing.Bitmap` and inadvertently hiding the base implementation. Bitmap also implements `GetPixel `which could be moved up to Image to be consistent with where `SetPixel `is implemented.

Note: In the full .NET Framework, `GetPixel` and `SetPixel` are not implemented in Image, only in `Bitmap` but if for design reasons `SetPixel` it is required in Image then it should be consistent and have `GetPixel` as well.

**Comment by Palomino34** [comment]
Done

**Comment by taylorza** [comment]
@dat, why override get and set pixel in Bitmap? The implementation is exactly the same as the inherited implementation. Not a big deal, but I was curious if there is a performance or some other benefit relating to the TinyCLR internals that would be useful to know.
