### ISSUE TITLE
USB Host Keyboard Disconnect - Inconsistent DeviceType

### ISSUE THREAD

**Issue by taylorza** [ghi-electronics/TinyCLR-Libraries#882]
This is a minor inconsistency. When connecting a keyboard the device type in the `ConnectionChangedEvent `is reported as `DeviceType.Keyboard`, however when disconnecting the keyboard the device is reported as `DeviceType.HID`. While technically correct, it would make sense for the disconnect state to indicate that it was a Keyboard being disconnected.

**Comment by Palomino34** [comment]
It will pick last interface when raise disconnect event, if more than 1 interface. Won't fix now.

User can use Id property to compare which is same all the time.
