### ISSUE TITLE
Implement system uptime

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#899]
.net Framework supplies GetTickCount().  We need something like that which returns the total run time since last reboot.

**Comment by gus-ghielec** [comment]
This is a useful feature but we think it can be done by the user. It will not be accurate but the point from this an overall system up time.

Alternately, use DateTime.now.tick for more accurate system tick. Of course setting the system time will change that but the user can easily track and calculate the "up time".

Feel free to explain what can't be done by the user and we must implement natively if there is another need we have missed.
