### ISSUE TITLE
Random.Next() can return negative number

### ISSUE THREAD

**Issue by bauland** [ghi-electronics/TinyCLR-Libraries#911]
Test with 2.1.0-preview4:
```
            var rnd = new Random();
            var nb = rnd.Next(100);

            Debug.WriteLine($"Number:{nb}");
```
Number is sometimes negative. But in https://docs.microsoft.com/fr-fr/dotnet/api/system.random.next?view=netframework-4.5.2, Next() is returning only non-negative number.

**Comment by gus-ghielec** [comment]
I think we switched to TRNG internally and that might be why. We will check.

**Comment by gus-ghielec** [comment]
Good catch but you have used an unreleased-for-testing-only preview4 that was not announced . We will fix this in the refresh of prevew4 that is happening tomorrow.
