### ISSUE TITLE
WinUSB on Linux

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#915]
It doesn't seem to work

**Comment by Palomino34** [comment]
It works now.

May need to add rule:

In /etc/udev/rules.d
 
Create a file called 99-ghi.rules with the following line in it
``` 
SUBSYSTEM==”usb”, ATTRS{idVendor}==”1b9f”, ATTR{idProduct}==”f006”, MODE=”0660”, GROUP=”plugdev”
```

Replace "1b9f" and "f006" by your PID and VID if needed.

**Comment by gus-ghielec** [comment]
Do we need to add this to docs?

**Comment by Palomino34** [comment]
I believe so

**Comment by Palomino34** [comment]
Done
