### ISSUE TITLE
Blocking, highly accurate delay

### ISSUE THREAD

**Issue by luca-panjer** [ghi-electronics/TinyCLR-Libraries#916]
Is it possible to get a super accurate delay function? Something like arduino has, delayMilliseconds(int i) and delayMicroseconds(int i). With a CPU this speed, maybe even a delayNanoseconds(int i) could be cool. I understand there is Thread.Sleep(), but this is only milliseconds and how accurate is this actually? The nice thing of the thread sleep is that it would be non blocking. This delay function would be blocking (to make the accuracy possible) so it would need to be used with care.

This kind of functionality would be very useful when, for example, toggling a pin high for x amount of microseconds and then pulling it low again. For such a simple scenario, it's overkill to use the signal generator class...

**Comment by gus-ghielec** [comment]
>> it's overkill to use the signal generator class...

It is not and it is designed for exactly what you are asking for. TinyCLR is made for real life applications so if you have a specific commercial need then please give us more details on what you need that can't be done with TinyCLR today.
