### ISSUE TITLE
Serial USB streams

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#920]
Look into changing the behavior of USB data stream read  to match network streams and look into adding serial stream.

**Comment by Palomino34** [comment]
Moved to doc:

https://github.com/ghi-electronics/Documentation/issues/521

**Comment by Palomino34** [comment]
CDC/WinUSB used stream to read/write already.
Uart moved to doc ghi-electronics/Documentation#521
