### ISSUE TITLE
QR code generator

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#934]
useful to show IP or website on screen to be captured by a phone's camera

**Comment by Palomino34** [comment]
It should be in Barcode folder;

namespace is "GHIElectronics.TinyCLR.Drivers.Barcode"  

use QRCodeReader for read.
use QRCodeWriter for write if support.

**Comment by Palomino34** [comment]
It should be in Barcode folder;

namespace is "GHIElectronics.TinyCLR.Drivers.Barcode"  

use QRCodeReader for read.
use QRCodeWriter for write if support.

**Comment by gus-ghielec** [comment]
Why not QRCodeGenerator?

**Comment by Palomino34** [comment]
That is fine

**Comment by gus-ghielec** [comment]
Check the license terms

**Comment by Palomino34** [comment]
move to drivers repo

**Comment by Palomino34** [comment]
Done.
