### ISSUE TITLE
Setting the device name results in duplicated USB name

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/TinyCLR-Libraries#937]
In Preview4 firmware, I set the Device Name : 
![image](https://user-images.githubusercontent.com/2230497/111038225-b81ec480-83dc-11eb-936b-b24d775c6611.png)

But this is what I ended up with:
![image](https://user-images.githubusercontent.com/2230497/111038232-c1a82c80-83dc-11eb-865e-b4fc87688575.png)

Note that the name got duplicated with an underscore in the middle.

**Comment by gus-ghielec** [comment]
This is how it has always been, from the old days. a fixed name but a name that can be changed and then it became the same name twice! Yes it needs ot be fixed.

**Comment by Palomino34** [comment]
Done.
