### ISSUE TITLE
NEC IR Decoder

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#938]
using System;
using System.Collections;
using System.Diagnostics;
using System.Text;
using System.Threading;
using GHIElectronics.TinyCLR.Devices.Gpio;

//NEC decoder https://techdocs.altium.com/display/FPGA/NEC+Infrared+Transmission+Protocol

// --- 9ms mark -- 4.5ms space -- 562us mark (space: 0= 562us, 1=1688us)
// 32bit message: 8bit address -- ~address -- 8bit command -- ~command
//  repeat -- 9ms mark --- 2.25ms space -- 562us mark

namespace GHIElectronics.TinyCLR.Drivers.Infrared {
    public class NeCIrDecoder {
        private Status status = Status.PreBurst;
        private const int BurstPreTime = 9000;
        private const int SpacePreTime = 4500;
        private const int BurstBitTime = 562;
        private const int ZeroBitTime = 562;
        private const int OneBitTime = 1688;
        private const int RepeatTime = 2250;
        private const int RepeatEndTime = 562;
        private long lastTick = DateTime.Now.Ticks;
        private uint necMessage = 0;
        private int bitIndex=0;
        public int errorCounter = 0;
        public NeCIrDecoder(GpioPin rx) {
            rx.SetDriveMode(GpioPinDriveMode.Input);
            this.lastTick = DateTime.Now.Ticks;
            rx.ValueChangedEdge = GpioPinEdge.FallingEdge | GpioPinEdge.RisingEdge;
            rx.DebounceTimeout = TimeSpan.FromMilliseconds(0);
            rx.ValueChanged += this.Rx_ValueChanged;

            this.status = Status.PreBurst;

        }
        private enum Status {
            PreBurst,
            PostPreBurst,
            RepeatEnd,
            BurstBit,
            DataBit,

        }
        private bool InRange(int value, int expected) {
            var lowMargin = 0.8;
            var highMargin = 1.2;
            if ((value > (expected * lowMargin)) && (value < (expected * highMargin)))
                return true;
            return false;
        }
        private void Rx_ValueChanged(GpioPin sender, GpioPinValueChangedEventArgs e) {

            var bitTime = (int)((e.Timestamp.Ticks - this.lastTick) / 10);
            this.lastTick = e.Timestamp.Ticks;

            switch (this.status) {
                case Status.PreBurst:
                    if (this.InRange(bitTime, BurstPreTime)) {
                        this.status = Status.PostPreBurst;
                        this.necMessage = 0;
                        this.bitIndex = 0;
                    }
                    break;
                case Status.PostPreBurst:
                    if (this.InRange(bitTime, SpacePreTime))
                        this.status = Status.BurstBit;
                    else if (this.InRange(bitTime, RepeatTime)) {
                        this.status = Status.RepeatEnd;
                    }
                    else {
                        this.errorCounter++;
                        this.status = Status.PreBurst;//error, go back!
                    }
                    break;
                case Status.RepeatEnd:
                    if (this.InRange(bitTime, RepeatEndTime)) {
                        //event this
                        Debug.WriteLine("Repeat!");
                    }
                    else {
                        this.errorCounter++;
                        this.status = Status.PreBurst;//error, go back!
                    }
                    break;
                case Status.BurstBit:
                    if (this.InRange(bitTime, BurstBitTime))
                        this.status = Status.DataBit;
                    else {
                        this.errorCounter++;
                        this.status = Status.PreBurst;//error, go back!
                    }
                    break;
                case Status.DataBit:
                    this.status = Status.BurstBit;
                    if (this.InRange(bitTime, ZeroBitTime)) {
                        // we have a zero
                        this.bitIndex++;
                    }
                    else if (this.InRange(bitTime, OneBitTime)) {
                        //we have a one
                        this.necMessage |= (uint)((1 << this.bitIndex));
                        this.bitIndex++;
                    }
                    else {
                        this.errorCounter++;
                        this.status = Status.PreBurst;//error, go back!
                    }
                    if (this.bitIndex == 32) {
                        var b0 = (byte)(this.necMessage >> 0);
                        var b1 = (byte)~(this.necMessage >> 8);
                        var b2 = (byte)(this.necMessage >> 16);
                        var b3 = (byte)~(this.necMessage >> 24);
                        if ((b0 == b1) && (b2 == b3)) {
                            //event this
                            var address = b0;
                            var command = b2;
                            Debug.WriteLine("Address: " + address + " - Command: " + command);
                        }
                        else {
                            this.errorCounter++;
                        }

                        this.status = Status.PreBurst;// we are good to restart
                        
                    }
                    break;
                default:
                    // why are we here?!!
                    this.status = Status.PreBurst;
                    break;

            }
        }

    }

}

**Comment by Palomino34** [comment]
Done
