### ISSUE TITLE
Application.Lock brings in GHIElectronics.TinyCLR.Networking

### ISSUE THREAD

**Issue by taylorza** [ghi-electronics/TinyCLR-Libraries#945]
The need to lock an application requires GHIElectronics.TinyCLR.Update which depends on GHIElectronics.TinyCLR.Networking, this increases the deployment size by 12,564 bytes even if networking is not required. In my case I am only locking the device to gain access to the CDC and WinUSB.

**Comment by Palomino34** [comment]
Network and Pin nugets are removed.

**Comment by taylorza** [comment]
@Palomino34 - Ideally we should pull the Application class out of the GHIElectronics.TinyCLR.Update assembly. If, as in my case, the only need is to Lock the application to access WinUSB, this still pulls in GHIElectronics.TinyCLR.IO which is +/- 20KB, which is needed for the IFU support.

**Comment by gus-ghielec** [comment]
Reworked the API for better interface and moved to native. See #971
