### ISSUE TITLE
deprecate IFU with streams

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/TinyCLR-Libraries#988]
IFU streams has proven itself to be problematic and doesn't fit every commercial need. We have new IFU way that works much better and also works on every hardware and chip variant! 

Clean up and mark old stuff deprecated.

**Comment by Palomino34** [comment]
Done. Removed

**Comment by gus-ghielec** [comment]
Keeping the old API alongside the new API was impossibly. Old API was removed but the internal structure are backwards compatible.
